<a href="https://colab.research.google.com/github/biruk-tafese/MachineLearingIntern/blob/main/FilterMethod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np

features = ["N","P","K","temperature","humidity","ph","rainfall","label"]
df = pd.read_csv("crop_recommendation.csv", names=features)



Prepare the data

In [13]:
df.shape


(2201, 8)

In [35]:
data = df.values
X = data[:,0:7]
Y = data[:,7]

Filter method

In [21]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [24]:
print(df.columns)


Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')


In [38]:
# Assuming 'label' is the column with crop names
categorical_feature = 'label'
print(df[categorical_feature].unique())


['label' 'rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee']


In [58]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

# Load the dataset
data = pd.read_csv('crop_recommendation.csv')

# Step 1: Encode Categorical Features (if any)
data = pd.get_dummies(data, columns=['label'], prefix='')

# Step 2: Convert Non-Numeric Data to Numeric (if any)
data['N'] = pd.to_numeric(data['N'])
data['P'] = pd.to_numeric(data['P'])
data['K'] = pd.to_numeric(data['K'])

# Step 3: Check column names and identify the correct target column
# print(data.columns)

# Step 4: Separate Features (X) and Target (Y)
X = data.drop(columns=['K'])  # Features without the target column
Y = data['K']  # Target, which is the target column

# Step 5: Feature extraction using SelectKBest
chi_best = SelectKBest(score_func=chi2, k=4)
k_best = chi_best.fit(X, Y)

# Summarize scores
np.set_printoptions(precision=3)
print(k_best.scores_)

k_features = k_best.transform(X)

# Summarize selected features
print(k_features[0:5, :])


[18145.006 33404.4     571.303  9041.321    33.646 24761.531  1041.012
   446.712   191.49   2100.      653.667   592.808   181.572  1041.012
   560.786   182.735   183.665   183.533   627.122   180.833   186.143
   457.699  1922.721   482.466   208.053   602.725   610.514   473.672]
[[ 90.     42.     82.003 202.936]
 [ 85.     58.     80.32  226.656]
 [ 60.     55.     82.321 263.964]
 [ 74.     35.     80.158 242.864]
 [ 78.     42.     81.605 262.717]]
